
[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
# family = "FiraCode Nerd Font"
# family = "Hack Nerd Font"
family = "JetBrainsMono Nerd Font"
# family = "BlexMono Nerd Font"

[window]
opacity = 0.90
# blur = false
# startup_mode = "SimpleFullscreen"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  # "~/.config/alacritty/rose-pine/rose-pine-moon.toml"
  "~/.config/alacritty/rose-pine/rose-pine.toml"
  # "~/.config/alacritty/roseprime.toml"
  # "~/.config/alacritty/zenbones/duckbones.toml"
  # "~/.config/alacritty/tokyonight/tokyonight_night.toml"
  # "~/.config/alacritty/kanagawa/kanagawa_dragon.toml"
]

[window.padding]
x = 7
y = 7

# [colors.primary]
# background = "#0a0a0a"
